<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'assets.packages' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/asset/Packages.php';
include_once $this->targetDirs[3].'/vendor/symfony/asset/PackageInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/asset/Package.php';
include_once $this->targetDirs[3].'/vendor/symfony/asset/PathPackage.php';
include_once $this->targetDirs[3].'/vendor/symfony/asset/VersionStrategy/VersionStrategyInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/asset/VersionStrategy/JsonManifestVersionStrategy.php';
include_once $this->targetDirs[3].'/vendor/symfony/asset/Context/ContextInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/asset/Context/RequestStackContext.php';

return $this->privates['assets.packages'] = new \Symfony\Component\Asset\Packages(new \Symfony\Component\Asset\PathPackage('', new \Symfony\Component\Asset\VersionStrategy\JsonManifestVersionStrategy(($this->targetDirs[3].'/public/build/manifest.json')), new \Symfony\Component\Asset\Context\RequestStackContext(($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), '', false)), []);
