<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Agilicode\QAT\Event\Subscriber\ReportCollectingSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/Event/Subscriber/ReportCollectingSubscriber.php';
include_once $this->targetDirs[3].'/src/Interfaces/CollectorInterface.php';
include_once $this->targetDirs[3].'/src/Collector/ChainCollector.php';
include_once $this->targetDirs[3].'/src/Collector/CucumberJsonCollector.php';
include_once $this->targetDirs[3].'/src/Collector/JUnitCollector.php';
include_once $this->targetDirs[3].'/src/Collector/Crap4jCollector.php';
include_once $this->targetDirs[3].'/src/Collector/CloverCollector.php';
include_once $this->targetDirs[3].'/src/Collector/PhpmetricLogCollector.php';
include_once $this->targetDirs[3].'/vendor/symfony/serializer/Encoder/EncoderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/serializer/Encoder/DecoderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/serializer/Encoder/JsonEncoder.php';
include_once $this->targetDirs[3].'/vendor/symfony/filesystem/Filesystem.php';
include_once $this->targetDirs[3].'/vendor/symfony/serializer/Encoder/NormalizationAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/serializer/SerializerAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/serializer/SerializerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/serializer/Encoder/XmlEncoder.php';

$a = ($this->privates['serializer.encoder.json'] ?? ($this->privates['serializer.encoder.json'] = new \Symfony\Component\Serializer\Encoder\JsonEncoder()));
$b = ($this->services['serializer'] ?? $this->load('getSerializerService.php'));
$c = ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem()));
$d = ($this->privates['serializer.encoder.xml'] ?? ($this->privates['serializer.encoder.xml'] = new \Symfony\Component\Serializer\Encoder\XmlEncoder()));

return $this->privates['Agilicode\\QAT\\Event\\Subscriber\\ReportCollectingSubscriber'] = new \Agilicode\QAT\Event\Subscriber\ReportCollectingSubscriber(new \Agilicode\QAT\Collector\ChainCollector([0 => new \Agilicode\QAT\Collector\CucumberJsonCollector($a, $b), 1 => new \Agilicode\QAT\Collector\JUnitCollector($b, $c, $d), 2 => new \Agilicode\QAT\Collector\Crap4jCollector($b, $c, $d), 3 => new \Agilicode\QAT\Collector\CloverCollector($b, $c, $d), 4 => new \Agilicode\QAT\Collector\PhpmetricLogCollector($b, $a, $c)]));
