<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Agilicode\QAT\Command\ReportCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/ReportCommand.php';

$this->privates['Agilicode\\QAT\\Command\\ReportCommand'] = $instance = new \Agilicode\QAT\Command\ReportCommand(($this->privates['workflow.registry'] ?? $this->load('getWorkflow_RegistryService.php')), ($this->services['qat.container.projects'] ?? $this->load('getQat_Container_ProjectsService.php')));

$instance->setName('report');

return $instance;
