<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Agilicode\QAT\Event\Subscriber\ReportRenderingSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/Event/Subscriber/ReportRenderingSubscriber.php';
include_once $this->targetDirs[3].'/src/Interfaces/RendererInterface.php';
include_once $this->targetDirs[3].'/src/Renderer/ChainRenderer.php';
include_once $this->targetDirs[3].'/vendor/symfony/filesystem/Filesystem.php';

return $this->privates['Agilicode\\QAT\\Event\\Subscriber\\ReportRenderingSubscriber'] = new \Agilicode\QAT\Event\Subscriber\ReportRenderingSubscriber(new \Agilicode\QAT\Renderer\ChainRenderer(), ($this->services['twig'] ?? $this->load('getTwigService.php')), ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), $this->parameters['qat.report.config']);
