<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'state_machine.qa_report.listener.audit_trail' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/workflow/EventListener/AuditTrailListener.php';

$a = new \Symfony\Bridge\Monolog\Logger('workflow');
$a->pushHandler(($this->privates['monolog.handler.console'] ?? ($this->privates['monolog.handler.console'] = new \Symfony\Bridge\Monolog\Handler\ConsoleHandler(NULL, true, []))));
$a->pushHandler(($this->privates['monolog.handler.main'] ?? $this->getMonolog_Handler_MainService()));

return $this->privates['state_machine.qa_report.listener.audit_trail'] = new \Symfony\Component\Workflow\EventListener\AuditTrailListener($a);
