<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'workflow.registry' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/workflow/Registry.php';
include_once $this->targetDirs[3].'/vendor/symfony/workflow/SupportStrategy/WorkflowSupportStrategyInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/workflow/SupportStrategy/InstanceOfSupportStrategy.php';

$this->privates['workflow.registry'] = $instance = new \Symfony\Component\Workflow\Registry();

$instance->addWorkflow(($this->services['state_machine.qa_report'] ?? $this->load('getStateMachine_QaReportService.php')), new \Symfony\Component\Workflow\SupportStrategy\InstanceOfSupportStrategy('Agilicode\\QAT\\Entity\\StateMachine\\ReportStateMachine'));

return $instance;
