<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOopV8Np\srcAgilicode_QAT_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOopV8Np/srcAgilicode_QAT_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOopV8Np.legacy');

    return;
}

if (!\class_exists(srcAgilicode_QAT_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOopV8Np\srcAgilicode_QAT_KernelDevDebugContainer::class, srcAgilicode_QAT_KernelDevDebugContainer::class, false);
}

return new \ContainerOopV8Np\srcAgilicode_QAT_KernelDevDebugContainer([
    'container.build_hash' => 'OopV8Np',
    'container.build_id' => 'a728a521',
    'container.build_time' => 1556615431,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOopV8Np');
